language: python
dist: focal
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10-dev"
install: "pip install flake8 mypy"
script:
  - "flake8 --max-line-length=120 dnscl.py dnscl_pihole.py dnscl_tail.py"
  - "mypy dnscl_tail.py"
