matrix:
  include:
    - os: linux
      dist: bionic
    - os: osx
    - os: windows
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
install: "pip install pylint"
script: "pylint dnscl.py"
